### PR TITLE
impement treetable tab

### PR DESCRIPTION
**Pull request by javierluraschi**
This PR implements a table view for profvis.

- [x] Add entry points for treetable
- [x] Generate table structure in d3 with profvis data
- [x] Format treetable
- [x] Add drill-down support per function
- [x] Memory and time percentage bars
- [x] Add count column and support to aggregate callstacks
- [x] Integrate with profvis options
- [x] Go-to-sources with row-highlighting

### CODE REVIEW

**Comment by javierluraschi** [comment]
Quick sketch of the table structure...

treetable

and the toolbar entry...

screen shot 2016-03-29 at 10 13 54 am

**Comment by javierluraschi** [comment]
Now with some data...

screen shot 2016-03-29 at 3 52 09 pm

**Comment by javierluraschi** [comment]
screen shot 2016-03-30 at 4 36 59 pm

**Comment by javierluraschi** [comment]
Showing only entries where "the entry has children" to resemble a compact callstack rather than a full code view.

screen shot 2016-03-30 at 8 39 32 pm

**Comment by javierluraschi** [comment]
screen shot 2016-03-31 at 8 40 53 am

**Comment by javierluraschi** [comment]
Aggregation and count column. Missing to integrate a couple smaller futures before this is ready to merge, almost there...

screen shot 2016-03-31 at 1 55 10 pm

**Comment by javierluraschi** [comment]
screen shot 2016-04-01 at 1 32 18 am

**Comment by jjallaire** [comment]
The new Table view is looking great!

I think we should use slightly more descriptive names for the tabs. Perhaps:

- Flame Graph
- (not sure what do use for Map)
- Data

I don't have an opinion about what these should be other than I think that
"Graph", "Table", and "Map" aren't very descriptive.

**Comment by javierluraschi** [comment]
@wch @hadley @jjallaire Ready to take feedback, I'll address it today. Thanks!

**Comment by javierluraschi** [comment]
"Flame Graph", "Data Table" and "Treemap"?

screen shot 2016-04-01 at 8 21 56 am

**Comment by jjallaire** [comment]
How about "Flame Graph", "Treemap", and "Profile Data" in that order?

**Comment by hadley** [comment]
The problem with treemap is that it has a specific technical meaning that is not true here (unless I misunderstand what is behind that tab)

**Comment by hadley** [comment]
Looking at the data table, is there a reason that expression isn't on the far left? That would seem most natural to me (and maybe the column should be called "Code").

Also the connection between the bar charts and the corresponding numbers seems a bit weak visually - i.e. it looks like the time bars correspond to the memory numbers. (But I don't have any great idea on how to improve it).  Could you move the units out of the columns and put in the column headings? (i.e. "Memory (MB)")

**Comment by javierluraschi** [comment]
@hadley This is what is behind the treemap tab. It borrows inspiration from the proftools treemap view.

screen shot 2016-04-01 at 11 00 13 am

**Comment by hadley** [comment]
Oh, that is a treemap, so it is the correct name. But I'm really not a fan of that as a visualisation technique - and if you are going to include it, I think it needs a some work to make the hierarchy more clear.

**Comment by javierluraschi** [comment]
@hadley Agree. I was really excited before implementing the treemap, now that it's implemented, I don't feel strongly about it. It seemed useful in theory, but in practice, it's not. My preference is to keep the treemap around and get additional feedback in dailies and improve if there is interest, but if we feel strongly against it, might be worth pulling the plug now.

**Comment by hadley** [comment]
I think you should pull the plug now.

**Comment by javierluraschi** [comment]
Pulled! Some improvements... Thoughts?

screen shot 2016-04-01 at 1 56 03 pm

**Comment by javierluraschi** [comment]
@hadley Regarding column order, I do have a couple good arguments for keeping columns as they are:
 1. While investigating profiles in details, the footprint (time, calls and memory) are more important than the code. Personally, I would scan for those columns with the most calls or time and drill down based on them. Is not until I narrowed than the problem that I start reading function names.
 2. Other profilers followed this convention, probably, for the same reasons.

**Comment by hadley** [comment]
Columns look a lot better. I think it's better to have code on the right because:

* then it's more like a bar chart where labels are on the left

* I think R users in general need a bit more scaffolding than programmers. Having the code first will help people situate themselves

**Comment by javierluraschi** [comment]
Renaming "Count" column to "Calls", make more sense to me.

screen shot 2016-04-01 at 2 03 25 pm

**Comment by javierluraschi** [comment]
Fair enough... updated. It still feels to me more natural to start with the numeric fields first, but I'll keep it with code-first unless someone else chimes-in for the numeric-first approach. Seems to me this is wrapping up, any other changes?

screen shot 2016-04-01 at 2 15 36 pm

**Comment by hadley** [comment]
That looks way better to me - thanks!

**Comment by jjallaire** [comment]
I still really dislike the name "Data Table". How about just "Profile Data"?

**Comment by javierluraschi** [comment]
You originally suggested "Data", we can use that header as well, changed. Let me know if you prefer "Profile Data" instead.

screen shot 2016-04-01 at 2 37 25 pm

**Comment by jjallaire** [comment]
I'd say "Data"

**Comment by javierluraschi** [comment]
Merging this iteration, ping me for additional improvements.

**Pull request merged**
