### PR TITLE
implement toolbar and visual improvements

### PR DESCRIPTION
**Pull request by javierluraschi**
Here is the baseline from Paul regarding integration improvements...

profiler improvements

and these are the changes performed in this PR. I'm planning to implement the new tabs (Call graph, Functions, Lines and Hot paths) with a separate PR:

screen shot 2016-03-07 at 1 28 54 pm - crop

Notice that the `x-axis` differs a bit from the base design. After I implemented this with the margin restrictions, I noticed that there is non-ideal cropping  and therefore, I suggest we keep the axis fully expanded (as implemented in this PR) to prevent the following issue.

screen shot 2016-03-07 at 2 39 38 pm - crop

### CODE REVIEW

**Comment by javierluraschi** [comment]
@wch @jjallaire: Would we prefer the smaller `x-axis`? Do you share my concern with cropping content over the axis edge? Any other comments and suggestions? Thanks!

**Comment by jjallaire** [comment]
I prefer your alternate treatment with the full width x-axis.

**Comment by wch** [comment]
I agree -- full-width axis looks better. If you feel that this is ready to merge, go for it!

**Comment by javierluraschi** [comment]
Alright, lets check this in then!

**Pull request merged**
