### PR TITLE
Add `print()` argument to sort alphabetically

### LINKED ISSUE #115: Partially aggregated samples of repeated function calls
In my use cases, I call a lot of fast functions repeatedly, and flame graphs help me understand how the computation times adds up. I like `pprof` because the flame graphs fully aggregate the samples of each function. Below, it is easy to see that `h()` is more of a bottleneck than `g()`.

```r
f <- function(...) {
  file <- tempfile()
  g(file)
  h(file)
  unlink(file)
  invisible()
}

g <- function(file) {
  writeLines("lorem ipsum", file)
}

h <- function(file) {
  digest::digest(file)
}

rprof <- tempfile()
pprof <- tempfile()
Rprof(filename = rprof)
replicate(1e3, f())
Rprof(NULL)
samples <- profile::read_rprof(rprof)
profile::write_pprof(samples, pprof)
system2(
  "/home/landau/go/bin/pprof",
  c("-http", "0.0.0.0:8080", pprof)
)
```

Screenshot_20191126_163811

I want to use `profvis` instead of `pprof` because it is much easier to install and use, but the flame graphs only partially aggregate the samples, which makes interpretation more difficult. Below,  `g()` and `h()` appear in multiple places, so I cannot tell which one is more of a bottleneck. 

``` r
packageDescription("profvis")$GithubSHA1
#> [1] "51b0671d65ac4329eef989ca36121f13c5f87c8c"
  
f <- function(...) {
  file <- tempfile()
  g(file)
  h(file)
  unlink(file)
  invisible()
}

g <- function(file) {
  writeLines("lorem ipsum", file)
}

h <- function(file) {
  digest::digest(file)
}

profvis::profvis(replicate(1e3, f()))
```

<sup>Created on 2019-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by lionel-**
Closes #115

Adds new `print()` argument `sort` which can take `"time"` (historical sorting, the default) and `"alphabetical"` values. The default can be changed with the `profvis.sort` global option. Sorting alphabetically produces the same sort of flamegraphs discussed in https://queue.acm.org/detail.cfm?id=2927301.

Edit: The print argument is now `aggregate` (takes a boolean) and the global option is `profvis.aggregate` (idem).

We might want to consider making this sorting the default as it makes it much more likely to merge the boxes within rows:

Screenshot 2020-12-02 at 15 34 45

Ideally, would be togglable from the web UI. For convenience the sorting is implemented in R, but we could generate both data frames upfront.

### CODE REVIEW

**Comment by wch** [comment]
That looks nice! I really think that this needs to be done from the web UI, though.

**Comment by wch** [comment]
Instead of alphabetical sorting, I think it would be helpful to sort by longest bar on top. I believe this is what the Data view does. It's helpful in that the things that are furthest to the left are also the most expensive (and therefore the first things to look at optimizing).

**Comment by lionel-** [comment]
Good idea. We now sort within rows by aggregated time. Given this change, I have changed the argument from `sort = c("time", "alphbetical")` to `aggregate = FALSE`. When `TRUE` the new sort is used.

To make it togglable from the UI we could generate upfront the two sorts of the data and send both to the JS side. It is possible that the implementation of the `Data` tab could be simplified by using the data sorted on the R side. That would have the advantages of easier maintenance from R and greater unit testing coverage.

In the meantime should we change the default to `TRUE`? It seems like this is the most useful view of the data.

**Comment by wch** [comment]
I'd prefer to keep the default order the same... I think the change would be confusing for people, and I do think the ordered view is useful for understanding the connection between the flow of the program and performance. This is especially true when profiling complex code. When the GUI has an obvious toggle switch for it, then users will have the best of both worlds.

**Comment by hadley** [comment]
Could we please try and wrap this PR and get it merged? I've already found the sorting useful in a couple of places.

**Pull request merged**
