### PR TITLE
Add syntax highlighting for R code

### PR DESCRIPTION
**Pull request by jimhester**
The highlighting contains only R from (https://highlightjs.org/download/) and uses the default style. If you like a different highlighting style it could use any of them from https://highlightjs.org/static/demo/ by adding the style and switching the yaml file.

Could also include all the styles and allow the user to choose, but I wanted to start simply.

### CODE REVIEW

**Comment by hadley** [comment]
:+1:

I assume this will also need an update to Authors@R to comply with what CRAN wants.

**Comment by jjallaire** [comment]
Another way to go here would be to use the customized version of highlight.js that we use in rmarkdown:

https://github.com/rstudio/rmarkdown/tree/master/inst/rmd/h/highlight

The `textmate.css` theme matches the syntax highlighting of the RStudio IDE exactly. This version of highlight.js was modified by @jcheng5 to be a bit more sophisitcated in it's highlighting of R code: https://github.com/rstudio/highlight.js/commits/r

**Comment by jimhester** [comment]
Added the highlight.js authors to `Authors@R` with 2dcc73f.

Having the syntax match rmarkdown seems reasonable and consistent. I have a branch with this (https://github.com/jimhester/profvis/tree/syntax_highlighting_rmarkdown) but the highlighting isn't working, it isn't adding the highlight classes or `<span>` blocks, so it is js rather than css issue. That version of highlight.js (6.2.0) still provides a `hljs.highlightBlock()` function, but perhaps it requires the code to be in `<code>` blocks?

Maybe we could track a more recent version of highlight.js for rmarkdown, the files currently have a significant diff and I think highlight.js has had at least one large refactor since it was forked.

```diff
--- r.js-rmarkdown	2015-12-06 10:47:31.177121109 -0500
+++ r.js-9.0.0	2015-12-06 10:47:02.601121620 -0500
@@ -1,139 +1,62 @@
 /*
 Language: R
 Author: Joe Cheng <joe@rstudio.org>
+Category: scientific
 */
 
-hljs.LANGUAGES.r = {
-  defaultMode: {
+function(hljs) {
+  var IDENT_RE = '([a-zA-Z]|\\.[a-zA-Z.])[a-zA-Z0-9._]*';
+
+  return {
     contains: [
       hljs.HASH_COMMENT_MODE,
-
+      {
+        begin: IDENT_RE,
+        lexemes: IDENT_RE,
+        keywords: {
+          keyword:
+            'function if in break next repeat else for return switch while try tryCatch ' +
+            'stop warning require library attach detach source setMethod setGeneric ' +
+            'setGroupGeneric setClass ...',
+          literal:
+            'NULL NA TRUE FALSE T F Inf NaN NA_integer_|10 NA_real_|10 NA_character_|10 ' +
+            'NA_complex_|10'
+        },
+        relevance: 0
+      },
       {
         // hex value
         className: 'number',
-        begin: "\\b0[xX][0-9a-fA-F]+[Li]?\\b",
-        end: hljs.IMMEDIATE_RE,
+        begin: "0[xX][0-9a-fA-F]+[Li]?\\b",
         relevance: 0
       },
       {
         // explicit integer
         className: 'number',
-        begin: "\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",
-        end: hljs.IMMEDIATE_RE,
+        begin: "\\d+(?:[eE][+\\-]?\\d*)?L\\b",
         relevance: 0
       },
       {
         // number with trailing decimal
         className: 'number',
-        begin: "\\b\\d+\\.(?!\\d)(?:i\\b)?",
-        end: hljs.IMMEDIATE_RE,
-        relevance: 1
+        begin: "\\d+\\.(?!\\d)(?:i\\b)?",
+        relevance: 0
       },
       {
         // number
         className: 'number',
-        begin: "\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",
-        end: hljs.IMMEDIATE_RE,
+        begin: "\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",
         relevance: 0
       },
       {
         // number with leading decimal
         className: 'number',
         begin: "\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",
-        end: hljs.IMMEDIATE_RE,
-        relevance: 1
-      },
-
-      {
-        className: 'keyword',
-        begin: "(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",
-        end: hljs.IMMEDIATE_RE,
-        relevance: 10
-      },
-      {
-        // ...
-        className: 'keyword',
-        begin: "\\.\\.\\.",
-        end: hljs.IMMEDIATE_RE,
-        relevance: 10
-      },
-      {
-        // ..1, ..2, etc.
-        className: 'keyword',
-        begin: "\\.\\.\\d+(?![\\w.])",
-        end: hljs.IMMEDIATE_RE,
-        relevance: 10
-      },
-      {
-        className: 'keyword',
-        begin: "\\b(?:function)",
-        end: hljs.IMMEDIATE_RE,
-        relevance: 2
-      },
-      {
-        className: 'keyword',
-        begin: "(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",
-        end: hljs.IMMEDIATE_RE,
-        relevance: 1
-      },
-      {
-        className: 'literal',
-        begin: "(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",
-        end: hljs.IMMEDIATE_RE,
-        relevance: 10
-      },
-      {
-        className: 'literal',
-        begin: "(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",
-        end: hljs.IMMEDIATE_RE,
-        relevance: 1
-      },
-      {
-        className: 'identifier',
-        begin: "[a-zA-Z.][a-zA-Z0-9._]*\\b",
-        end: hljs.IMMEDIATE_RE,
-        relevance: 0
-      },
-
-      {
-        // high relevance for common R case of non-numeric assignment
-        className: 'operator',
-        begin: '<\\-(?!\\s*\\d)',
-        end: hljs.IMMEDIATE_RE,
-        relevance: 2  // Let's not go crazy because Haskell uses this too
-      },
-      {
-        // higher relevance for unusual operator
-        className: 'operator',
-        begin: '\\->|<\\-',
-        end: hljs.IMMEDIATE_RE,
-        relevance: 1
-      },
-      {
-        className: 'operator',
-        begin: '%%|~',
-        end: hljs.IMMEDIATE_RE
-      },
-      {
-        // common operators
-        className: 'operator',
-        begin: '>=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:',
-        end: hljs.IMMEDIATE_RE,
         relevance: 0
       },
 
       {
-        // infix operator
-        className: 'operator',
-        begin: '%',
-        end: '%',
-        illegal: '\\n',
-        relevance: 1
-      },
-
-      {
         // escaped identifier
-        className: 'identifier',
         begin: '`',
         end: '`',
         relevance: 0
@@ -141,27 +64,12 @@
 
       {
         className: 'string',
-        begin: '"',
-        end: '"',
         contains: [hljs.BACKSLASH_ESCAPE],
-        relevance: 0
-      },
-      {
-        className: 'string',
-        begin: "'",
-        end: "'",
-        contains: [hljs.BACKSLASH_ESCAPE],
-        relevance: 0
-      },
-
-      {
-        className: 'paren',
-        begin: '[[({\\])}]',
-        end: hljs.IMMEDIATE_RE,
-        relevance: 0
+        variants: [
+          {begin: '"', end: '"'},
+          {begin: "'", end: "'"}
+        ]
       }
-
     ]
-  }
-};
-
+  };
+}
```

**Comment by jjallaire** [comment]
I think you should either use all of the highlight.js embedded in rmarkdown
or you should use the newer highlight.js that doesn't match rmarkdown.
Mixing them will require you to go back into Joe's customized version of
highlight.js and tease out what the changes were and then re-apply them to
the newer highlights.js. Not worth it IMO.

**Comment by jimhester** [comment]
@jjallaire In https://github.com/jimhester/profvis/tree/syntax_highlighting_rmarkdown I used all of Joe's customized verson of highlight.js from the rmarkdown.

In https://github.com/rstudio/profvis/commit/2dcc73f2709243e8385b8c3552ee27323e943fd4 it uses only the new highlight.js.

So there is no mixing of the two involved, sorry if this was unclear in my previous reply. I showed the diff solely to show the divergence between the two forks.

I am still unsure why Joe's version wasn't working properly, I unfortunately didn't have very much time over the weekend to figure it out.

**Comment by jjallaire** [comment]
Okay, I get it now, thanks for the clarification!

**Comment by wch** [comment]
This will be a useful addition!

Some comments/issues:

* The highlighting is subtle, and doesn't look to me like the syntax highlighting in rmarkdown or the IDE. For example:

rmarkdown:
image

profvis (this PR):
image


* The code no longer wraps for long lines, so it's easily possible for the time/percent/bar to be hidden from view. See screenshot below.
* The table cells change height when they're clicked (and the black lines are added to the top and bottom), but they shouldn't. Also, the lines don't run straight all the way across the table. See screenshot below.

master:
image

This PR:
image

* This highlights each row individually. This will probably result in incorrect output for things that span multiple lines. For example, everything below is in a string and should be colored the same, but if it's processed on a line-by-line basis, it'll treat the middle line as code instead of as a string. I think that what's needed is to highlight all the code in one DOM element, then pull it apart into separate lines and insert it into the table. That'll be a lot more work though!

    ```R
    "x
    1 == + 2
    x"
    ```

* Instead of highlighting on `$(document).ready()`, the highlighting should occur in the `generateCodeTable` function. (With the current code, highlighting doesn't work properly in knitr documents, because it's not happening at the right time.)

**Comment by jimhester** [comment]
> The highlighting is subtle, and doesn't look to me like the syntax highlighting in rmarkdown or the IDE.

The fix for this is to do as JJ suggested and use the highlight.js and css files from rmarkdown. This is now working with https://github.com/jimhester/profvis/commit/0ad65c3baa39135b103e3dadb3271be5dac39604 (the reason it wasn't working previously is highlight.js needed the language on the block to be explicitly set to `r`).

> The code no longer wraps for long lines, so it's easily possible for the time/percent/bar to be hidden from view. See screenshot below.

This seems to be fixed (on my machine) when using the rmarkdown highlight.js.

> The table cells change height when they're clicked (and the black lines are added to the top and bottom), but they shouldn't. Also, the lines don't run straight all the way across the table. See screenshot below.

These also seem to be fixed when using the rmarkdown highlight.js.

> This highlights each row individually.

This is true, and a limitation I was aware of when I sent the pull request. The fix as you said is to have all the code in one block and highlight that, but that would require a major refactor of the table generation logic.

> Instead of highlighting on $(document).ready(), the highlighting should occur in the generateCodeTable function.

I am not exactly sure how to get highlighting working within `generateCodeTable`, doing something akin to the following doesn't work. Suggestions welcome!
```diff
diff --git a/inst/htmlwidgets/lib/profvis/profvis.js b/inst/htmlwidgets/lib/profvis/profvis.js
index 7e4acff..6372607 100644
--- a/inst/htmlwidgets/lib/profvis/profvis.js
+++ b/inst/htmlwidgets/lib/profvis/profvis.js
@@ -185,9 +185,10 @@ profvis = (function() {
         .attr("class", "linenum")
         .text(function(d) { return d.linenum; });

-      rows.append("td")
-        .attr("class", "code")
-        .text(function(d) { return d.content; });
+      code = rows.append("td")
+        .attr("class", "code r")
+        .text(function(d) { return d.content; })
+      hljs.highlightBlock(code);

       rows.append("td")
         .attr("class", "time")
@@ -1825,12 +1826,5 @@ profvis = (function() {
     };
   }

-  $(document).ready(function() {
-    $('td.code').each(function(i, block) {
-      $(this).addClass("r");
-      hljs.highlightBlock(block);
-    });
-  });
-
   return profvis;
 })();
```

**Comment by wch** [comment]
Everything does look much better with the latest changes, thanks. I would prefer that the code be highlighted across lines. Could you file an issue for that?


>> Instead of highlighting on $(document).ready(), the highlighting should occur in the generateCodeTable function.

> I am not exactly sure how to get highlighting working within generateCodeTable, doing something akin to the following doesn't work. Suggestions welcome!

This should do it:

```js
      rows.append("td")
        .attr("class", "code r")
        .text(function(d) { return d.content; })
        .each(function() { hljs.highlightBlock(this); });
```

One other thing: For jshint, `hljs` should be added to the list of globals at the top of `profvis.js`.

**Comment by jimhester** [comment]
Thanks Winston, I thought I tried something similar, but I think I was using `$(this)` instead of `this`. I clearly have not done enough JS programming to catch all of the subtleties. b87491d95e55f has your suggested change.

If you want me to squash all the commits into one let me know, otherwise this should be good to merge.

**Comment by wch** [comment]
Looks good! One more thing - can you add the relevant information in the `LICENSE` file at the top-level?

**Comment by jimhester** [comment]
Done https://github.com/jimhester/profvis/commit/2442064873d88287cc76d663a06e5b0a94117f44

**Pull request merged**
